-- ============================================================
-- PROJETO LÓGICO DE BANCO DE DADOS - E-COMMERCE
-- MySQL 8+
-- ============================================================

DROP DATABASE IF EXISTS ecommerce_dio;
CREATE DATABASE ecommerce_dio;
USE ecommerce_dio;

-- =========================
-- TABELAS PRINCIPAIS
-- =========================

CREATE TABLE CLIENTE (
    idCLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    IDENTIFICACAO VARCHAR(45) NOT NULL UNIQUE,
    ENDERECO VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(80),
    TELEFONE VARCHAR(20)
);

CREATE TABLE CLIENTE_PF (
    idCLIENTE_PF INT PRIMARY KEY,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    CONSTRAINT fk_cliente_pf_cliente
        FOREIGN KEY (idCLIENTE_PF) REFERENCES CLIENTE(idCLIENTE)
        ON DELETE CASCADE,
    CONSTRAINT chk_cpf_formato
        CHECK (CPF REGEXP '^[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}-[0-9]{2}$')
);

CREATE TABLE CLIENTE_PJ (
    idCLIENTE_PJ INT PRIMARY KEY,
    CNPJ VARCHAR(18) NOT NULL UNIQUE,
    RAZAO_SOCIAL VARCHAR(45) NOT NULL,
    CONSTRAINT fk_cliente_pj_cliente
        FOREIGN KEY (idCLIENTE_PJ) REFERENCES CLIENTE(idCLIENTE)
        ON DELETE CASCADE,
    CONSTRAINT chk_cnpj_formato
        CHECK (CNPJ REGEXP '^[0-9]{2}\\.[0-9]{3}\\.[0-9]{3}/[0-9]{4}-[0-9]{2}$')
);

CREATE TABLE FORMA_PAGAMENTO (
    idFORMA_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    STATUS VARCHAR(45) NOT NULL DEFAULT 'ATIVO',
    CONSTRAINT chk_status_forma_pagamento
        CHECK (STATUS IN ('ATIVO', 'INATIVO'))
);

CREATE TABLE FORMA_PAGAMENTO_has_CLIENTE (
    FORMA_PAGAMENTO_idFORMA_PAGAMENTO INT NOT NULL,
    CLIENTE_idCLIENTE INT NOT NULL,
    PRIMARY KEY (FORMA_PAGAMENTO_idFORMA_PAGAMENTO, CLIENTE_idCLIENTE),
    CONSTRAINT fk_fpag_cliente_fpag
        FOREIGN KEY (FORMA_PAGAMENTO_idFORMA_PAGAMENTO)
        REFERENCES FORMA_PAGAMENTO(idFORMA_PAGAMENTO),
    CONSTRAINT fk_fpag_cliente_cliente
        FOREIGN KEY (CLIENTE_idCLIENTE)
        REFERENCES CLIENTE(idCLIENTE)
        ON DELETE CASCADE
);

CREATE TABLE PRODUTO (
    idPRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA VARCHAR(45) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    CONSTRAINT chk_valor_produto
        CHECK (VALOR >= 0)
);

CREATE TABLE PEDIDO (
    idPEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    STATUS VARCHAR(45) NOT NULL,
    DESCRICAO VARCHAR(100),
    FRETE DECIMAL(10,2) NOT NULL DEFAULT 0,
    CLIENTE_idCLIENTE INT NOT NULL,
    DATA_PEDIDO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pedido_cliente
        FOREIGN KEY (CLIENTE_idCLIENTE)
        REFERENCES CLIENTE(idCLIENTE),
    CONSTRAINT chk_status_pedido
        CHECK (STATUS IN ('EM_PROCESSAMENTO', 'PAGO', 'ENVIADO', 'ENTREGUE', 'CANCELADO')),
    CONSTRAINT chk_frete
        CHECK (FRETE >= 0)
);

CREATE TABLE RELACAO_PRODUTO_PEDIDO (
    PEDIDO_idPEDIDO INT NOT NULL,
    PRODUTO_idPRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (PEDIDO_idPEDIDO, PRODUTO_idPRODUTO),
    CONSTRAINT fk_rel_pedido
        FOREIGN KEY (PEDIDO_idPEDIDO)
        REFERENCES PEDIDO(idPEDIDO)
        ON DELETE CASCADE,
    CONSTRAINT fk_rel_produto
        FOREIGN KEY (PRODUTO_idPRODUTO)
        REFERENCES PRODUTO(idPRODUTO),
    CONSTRAINT chk_qtd_pedido
        CHECK (QUANTIDADE > 0)
);

CREATE TABLE ENTREGA (
    idENTREGA INT AUTO_INCREMENT PRIMARY KEY,
    STATUS VARCHAR(45) NOT NULL,
    CODIGO_RASTREIO VARCHAR(45) UNIQUE,
    CONSTRAINT chk_status_entrega
        CHECK (STATUS IN ('AGUARDANDO_ENVIO', 'EM_TRANSPORTE', 'ENTREGUE', 'DEVOLVIDO'))
);

CREATE TABLE ENTREGA_has_PEDIDO (
    ENTREGA_idENTREGA INT NOT NULL,
    PEDIDO_idPEDIDO INT NOT NULL,
    PRIMARY KEY (ENTREGA_idENTREGA, PEDIDO_idPEDIDO),
    CONSTRAINT fk_entrega_pedido_entrega
        FOREIGN KEY (ENTREGA_idENTREGA)
        REFERENCES ENTREGA(idENTREGA),
    CONSTRAINT fk_entrega_pedido_pedido
        FOREIGN KEY (PEDIDO_idPEDIDO)
        REFERENCES PEDIDO(idPEDIDO)
        ON DELETE CASCADE
);

CREATE TABLE FORNECEDOR (
    idFORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(45) NOT NULL,
    CNPJ VARCHAR(18) NOT NULL UNIQUE,
    CONSTRAINT chk_cnpj_fornecedor
        CHECK (CNPJ REGEXP '^[0-9]{2}\\.[0-9]{3}\\.[0-9]{3}/[0-9]{4}-[0-9]{2}$')
);

CREATE TABLE DISPONIBILIZANDO_PRODUTO (
    FORNECEDOR_idFORNECEDOR INT NOT NULL,
    PRODUTO_idPRODUTO INT NOT NULL,
    PRIMARY KEY (FORNECEDOR_idFORNECEDOR, PRODUTO_idPRODUTO),
    CONSTRAINT fk_disp_fornecedor
        FOREIGN KEY (FORNECEDOR_idFORNECEDOR)
        REFERENCES FORNECEDOR(idFORNECEDOR),
    CONSTRAINT fk_disp_produto
        FOREIGN KEY (PRODUTO_idPRODUTO)
        REFERENCES PRODUTO(idPRODUTO)
);

CREATE TABLE VENDEDOR (
    idVENDEDOR INT AUTO_INCREMENT PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(45) NOT NULL,
    LOCAL VARCHAR(45) NOT NULL,
    CNPJ VARCHAR(18),
    CPF VARCHAR(14),
    CONSTRAINT chk_doc_vendedor
        CHECK (
            (CNPJ IS NOT NULL AND CPF IS NULL)
            OR
            (CNPJ IS NULL AND CPF IS NOT NULL)
        )
);

CREATE TABLE PRODUTOS_POR_VENDEDOR (
    VENDEDOR_idVENDEDOR INT NOT NULL,
    PRODUTO_idPRODUTO INT NOT NULL,
    PRIMARY KEY (VENDEDOR_idVENDEDOR, PRODUTO_idPRODUTO),
    CONSTRAINT fk_prod_vendedor_vendedor
        FOREIGN KEY (VENDEDOR_idVENDEDOR)
        REFERENCES VENDEDOR(idVENDEDOR),
    CONSTRAINT fk_prod_vendedor_produto
        FOREIGN KEY (PRODUTO_idPRODUTO)
        REFERENCES PRODUTO(idPRODUTO)
);

CREATE TABLE ESTOQUE (
    idESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
    LOCAL VARCHAR(45) NOT NULL
);

CREATE TABLE PRODUTO_has_ESTOQUE (
    PRODUTO_idPRODUTO INT NOT NULL,
    ESTOQUE_idESTOQUE INT NOT NULL,
    QUANTIDADE INT NOT NULL DEFAULT 0,
    PRIMARY KEY (PRODUTO_idPRODUTO, ESTOQUE_idESTOQUE),
    CONSTRAINT fk_prod_estoque_produto
        FOREIGN KEY (PRODUTO_idPRODUTO)
        REFERENCES PRODUTO(idPRODUTO),
    CONSTRAINT fk_prod_estoque_estoque
        FOREIGN KEY (ESTOQUE_idESTOQUE)
        REFERENCES ESTOQUE(idESTOQUE),
    CONSTRAINT chk_qtd_estoque
        CHECK (QUANTIDADE >= 0)
);
